# Generated by Django 6.0.5 on 2026-06-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="ai_model",
            field=models.CharField(
                choices=[
                    ("meta/llama-3.1-8b-instruct", "Llama 3.1 (8B) - Equilibrado"),
                    ("meta/llama-3.1-70b-instruct", "Llama 3.1 (70B) - Avanzado"),
                    ("google/gemma-2-2b-it", "Gemma 2 (2B) - Muy rápido"),
                    (
                        "mistralai/mistral-nemo-12b-instruct",
                        "Mistral Nemo (12B) - Alternativo",
                    ),
                ],
                default="google/gemma-2-2b-it",
                max_length=100,
            ),
        ),
    ]
