# Generated by Django 6.0.5 on 2026-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_ai_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
