# Generated by Django 6.0.5 on 2026-06-18 11:25

import chat.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_is_archived_conversation_is_pinned"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=chat.models.default_expiration),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_links",
                        to="chat.conversation",
                    ),
                ),
            ],
        ),
    ]
