# Generated by Django 6.0.5 on 2026-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_sharedlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="ai_model",
            field=models.CharField(
                choices=[
                    (
                        "meta/llama-3.3-70b-instruct",
                        "Llama 3.3 (70B) - Avanzado y actualizado",
                    ),
                    (
                        "deepseek-ai/deepseek-r1",
                        "DeepSeek R1 - Experto en razonamiento",
                    ),
                    ("google/gemma-2-2b-it", "Gemma 2 (2B) - Muy rápido"),
                    (
                        "mistralai/mistral-large-2-instruct",
                        "Mistral Large 2 - Alternativa potente",
                    ),
                ],
                default="google/gemma-2-2b-it",
                max_length=100,
            ),
        ),
    ]
