# Generated by Django 6.0.5 on 2026-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_conversation_ai_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="ai_model",
            field=models.CharField(
                choices=[
                    (
                        "meta/llama-3.3-70b-instruct",
                        "Llama 3.3 (70B) - Avanzado y actualizado",
                    ),
                    (
                        "deepseek-ai/deepseek-r1",
                        "DeepSeek R1 - Experto en razonamiento",
                    ),
                    ("google/gemma-2-2b-it", "Gemma 2 (2B) - Muy rápido"),
                    (
                        "mistralai/mixtral-8x22b-instruct-v0.1",
                        "Mixtral 8x22B - Alternativa estable",
                    ),
                ],
                default="google/gemma-2-2b-it",
                max_length=100,
            ),
        ),
    ]
