# Generated by Django 6.0.5 on 2026-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_conversation_ai_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="ai_model",
            field=models.CharField(
                choices=[
                    ("google/gemma-2-2b-it", "Gemma 2 (2B) - Ultra rápido"),
                    (
                        "meta/llama-3.1-8b-instruct",
                        "Llama 3.1 (8B) - Equilibrado y estable",
                    ),
                    (
                        "deepseek-ai/deepseek-v4-flash",
                        "DeepSeek V4 Flash - Optimizado y rápido",
                    ),
                    (
                        "deepseek-ai/deepseek-v4-pro",
                        "DeepSeek V4 Pro - Razonamiento profundo",
                    ),
                ],
                default="google/gemma-2-2b-it",
                max_length=100,
            ),
        ),
    ]
